---
layout: default
---

# HuBMAP EPICs Overview
Externally Processed Integrated Collection(s)

## What is an EPIC?
An EPIC (Externally Processed Integrated Collection) is a processed or analyzed dataset generated by a lab. The EPIC dataset could be derived by analyzing one or more primary or derived datasets. The dataset(s) processed to create the EPIC is considered the “parent” dataset (see Fig 1).

Examples:
- A lab generates a segmentation mask that identifies cells from a CODEx run. The segmentation mask is an EPIC (i.e., derived dataset), while the PhenoCycler imaging data is the primary dataset that is the parent dataset for the EPIC (see Fig 1). 
- A lab generates novel cell type annotations using a previously published (EPIC) segmentation mask. This novel set of annotations is new EPIC with the parent being the original segmentation mask EPIC. 
- A lab processes ten RNAseq datasets, generating a normalized cell by gene matrix and Azimuth cell annotations. This derived dataset. consisting of the normalized cell by gene matrix and cell type annotations, is a single EPIC even if the lab used a HuBMAP pipeline to process the ten RNAseq datasets. The ten RNAseq datasets are the parent datasets for this EPIC; that is, the EPIC dataset has ten parent datasets.
- A lab downloads a published, processed dataset that includes a cell by gene matrix. The lab generates a new set of cell type annotations. This new annotation set is an EPIC with the pre-existing processed dataset being the parent.
- A lab combines a set of 30 histology images into a (pseudo) 3D image, using a HuBMAP 3D reconstruction pipeline or any other 3D reconstruction pipeline. The 3D reconstruction is an EPIC with 30 parent datasets (i.e., the 30 histology datasets). If the lab generates 3D segmentation masks using the 3D reconstruction, then the 3D segmentation masks are a new EPIC with the parent being the single 3D reconstruction EPIC.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ![EPICs Figure 1](EPICs-Fig1.png)

**Figure 1:** EPIC dataset example (2D segmentation mask) and the upstream, parent dataset (PhenoCycler).

Please contact the [HuBMAP Helpdesk](help@hubmapconsortium.org), if you require assistance or have questions about EPICs.

## Types of EPICs
We’ve defined three types of EPICs: (1) segmentation masks, (2) object by analyte, and (3) 3D reconstruction. The three EPICs should support a broad range of analysis:
- Single assays results: multiomic (dissociated), spatial, volumetric
- Annotations: cell types and other structures in dissociated or spatial assays
- Annotations: 2D and 3D segmentations, naming of features, stacking 2D slices to construct a volume
- Annotations: Stacking multi-modal assays done on slices
- Annotations: Imputing expression in cells in ‘gaps between’ slices
  
There are currently no plans to define new types of EPICs. If you have derived data you would like to upload that doesn’t map to one of these dataset types, please contact the [HuBMAP Helpdesk](help@hubmapconsortium.org).
